//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Spix.xLanguage.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Spix.xLanguage.Resources.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active.
        /// </summary>
        public static string Active {
            get {
                return ResourceManager.GetString("Active", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address.
        /// </summary>
        public static string Address {
            get {
                return ResourceManager.GetString("Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back.
        /// </summary>
        public static string ButtonBack {
            get {
                return ResourceManager.GetString("ButtonBack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string ButtonCancel {
            get {
                return ResourceManager.GetString("ButtonCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm Email.
        /// </summary>
        public static string ButtonConfirmEmail {
            get {
                return ResourceManager.GetString("ButtonConfirmEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        public static string ButtonLogin {
            get {
                return ResourceManager.GetString("ButtonLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm Logout.
        /// </summary>
        public static string ButtonLogout {
            get {
                return ResourceManager.GetString("ButtonLogout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string ButtonSave {
            get {
                return ResourceManager.GetString("ButtonSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send.
        /// </summary>
        public static string ButtonSend {
            get {
                return ResourceManager.GetString("ButtonSend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cities.
        /// </summary>
        public static string Cities {
            get {
                return ResourceManager.GetString("Cities", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to City.
        /// </summary>
        public static string City {
            get {
                return ResourceManager.GetString("City", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A Transaction is already Active.
        /// </summary>
        public static string Context_Begin {
            get {
                return ResourceManager.GetString("Context_Begin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Active Transaction to Commit.
        /// </summary>
        public static string Context_Commit {
            get {
                return ResourceManager.GetString("Context_Commit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Active Transaction to Rollback.
        /// </summary>
        public static string Context_RollBack {
            get {
                return ResourceManager.GetString("Context_RollBack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Control Access.
        /// </summary>
        public static string ControlAccess {
            get {
                return ResourceManager.GetString("ControlAccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Corporation.
        /// </summary>
        public static string Corporation {
            get {
                return ResourceManager.GetString("Corporation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country.
        /// </summary>
        public static string Country {
            get {
                return ResourceManager.GetString("Country", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create User.
        /// </summary>
        public static string CreateUser {
            get {
                return ResourceManager.GetString("CreateUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current Password.
        /// </summary>
        public static string Current_Password {
            get {
                return ResourceManager.GetString("Current_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date End.
        /// </summary>
        public static string DateEnd {
            get {
                return ResourceManager.GetString("DateEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date Start.
        /// </summary>
        public static string DateStart {
            get {
                return ResourceManager.GetString("DateStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data concurrency conflict.
        /// </summary>
        public static string Db_Concurrency {
            get {
                return ResourceManager.GetString("Db_Concurrency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duplicate value in the database.
        /// </summary>
        public static string Db_Duplicate {
            get {
                return ResourceManager.GetString("Db_Duplicate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General database error.
        /// </summary>
        public static string Db_Error {
            get {
                return ResourceManager.GetString("Db_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reference error, invalid foreign key.
        /// </summary>
        public static string Db_Reference {
            get {
                return ResourceManager.GetString("Db_Reference", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Document.
        /// </summary>
        public static string Document {
            get {
                return ResourceManager.GetString("Document", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit User.
        /// </summary>
        public static string EditUser {
            get {
                return ResourceManager.GetString("EditUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email Confirmation.
        /// </summary>
        public static string EmailConfirmation {
            get {
                return ResourceManager.GetString("EmailConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It&apos;s necessary to confirm your email in order to activate your account.
        /// </summary>
        public static string EmailConfirmationMsg {
            get {
                return ResourceManager.GetString("EmailConfirmationMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email Confirmed.
        /// </summary>
        public static string EmailConfirmed {
            get {
                return ResourceManager.GetString("EmailConfirmed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your account has been successfully activated.
        /// </summary>
        public static string EmailConfirmedMsg {
            get {
                return ResourceManager.GetString("EmailConfirmedMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We&apos;ve sent you instructions to reset your password. Please check your inbox.
        /// </summary>
        public static string EmailSentMsg {
            get {
                return ResourceManager.GetString("EmailSentMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email Sent.
        /// </summary>
        public static string EmailSentTitle {
            get {
                return ResourceManager.GetString("EmailSentTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recovery Password.
        /// </summary>
        public static string EmailSubject {
            get {
                return ResourceManager.GetString("EmailSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End Date.
        /// </summary>
        public static string EndDate {
            get {
                return ResourceManager.GetString("EndDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Errors Invalid File Extension.
        /// </summary>
        public static string Errors_InvalidFileExtension {
            get {
                return ResourceManager.GetString("Errors_InvalidFileExtension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Errors_InvalidMimeType.
        /// </summary>
        public static string Errors_InvalidMimeType {
            get {
                return ResourceManager.GetString("Errors_InvalidMimeType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fax Number.
        /// </summary>
        public static string Fax_Number {
            get {
                return ResourceManager.GetString("Fax_Number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The MIME type does not match the file extension. Expected:.
        /// </summary>
        public static string file_CheckMime {
            get {
                return ResourceManager.GetString("file_CheckMime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only Documents files ( .doc .docx .PDF).
        /// </summary>
        public static string File_OnlyFiles {
            get {
                return ResourceManager.GetString("File_OnlyFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only image files (.jpg, .jpeg, .png) are allowed.
        /// </summary>
        public static string File_OnlyImage {
            get {
                return ResourceManager.GetString("File_OnlyImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First Name.
        /// </summary>
        public static string FirstName {
            get {
                return ResourceManager.GetString("FirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Full Name.
        /// </summary>
        public static string FullName {
            get {
                return ResourceManager.GetString("FullName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry, you do not have access to the system.
        /// </summary>
        public static string Generic_AccessDenied {
            get {
                return ResourceManager.GetString("Generic_AccessDenied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to retrieve authenticated user&apos;s email.
        /// </summary>
        public static string Generic_AuthEmailFail {
            get {
                return ResourceManager.GetString("Generic_AuthEmailFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to retrieve user identifier.
        /// </summary>
        public static string Generic_AuthIdFail {
            get {
                return ResourceManager.GetString("Generic_AuthIdFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must be logged in to access this resource.
        /// </summary>
        public static string Generic_AuthRequired {
            get {
                return ResourceManager.GetString("Generic_AuthRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to retrieve user role.
        /// </summary>
        public static string Generic_AuthRoleFail {
            get {
                return ResourceManager.GetString("Generic_AuthRoleFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The corporation you are trying to access is inactive, Please contact the system administrator.
        /// </summary>
        public static string Generic_CorporationInactive {
            get {
                return ResourceManager.GetString("Generic_CorporationInactive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This email is already associated with another account.
        /// </summary>
        public static string Generic_EmailAlreadyUsed {
            get {
                return ResourceManager.GetString("Generic_EmailAlreadyUsed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General exception with no specific cause.
        /// </summary>
        public static string Generic_Exception {
            get {
                return ResourceManager.GetString("Generic_Exception", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Malformed or invalid request.
        /// </summary>
        public static string Generic_Http_BadRequest {
            get {
                return ResourceManager.GetString("Generic_Http_BadRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We couldn&apos;t find what you were looking for.
        /// </summary>
        public static string Generic_IdNotFound {
            get {
                return ResourceManager.GetString("Generic_IdNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid username or password.
        /// </summary>
        public static string Generic_InvalidCredentials {
            get {
                return ResourceManager.GetString("Generic_InvalidCredentials", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There seems to be an issue with the information provided.
        /// </summary>
        public static string Generic_InvalidId {
            get {
                return ResourceManager.GetString("Generic_InvalidId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There was a problem with the data submitted.
        /// </summary>
        public static string Generic_InvalidModel {
            get {
                return ResourceManager.GetString("Generic_InvalidModel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tried to access a null value.
        /// </summary>
        public static string Generic_NullException {
            get {
                return ResourceManager.GetString("Generic_NullException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your plan has expired, please renew your account.
        /// </summary>
        public static string Generic_PlanExpired {
            get {
                return ResourceManager.GetString("Generic_PlanExpired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The record was deleted, but the image was not removed.
        /// </summary>
        public static string Generic_RecordDeletedNoImage {
            get {
                return ResourceManager.GetString("Generic_RecordDeletedNoImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Problems finding the specified record.
        /// </summary>
        public static string Generic_RegisterNotFound {
            get {
                return ResourceManager.GetString("Generic_RegisterNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Everything was completed successfully.
        /// </summary>
        public static string Generic_Success {
            get {
                return ResourceManager.GetString("Generic_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An unexpected error occurred. Please try again later.
        /// </summary>
        public static string Generic_UnexpectedError {
            get {
                return ResourceManager.GetString("Generic_UnexpectedError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The account is temporarily blocked.
        /// </summary>
        public static string Generic_UserBlocked {
            get {
                return ResourceManager.GetString("Generic_UserBlocked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not create the user. Please try again.
        /// </summary>
        public static string Generic_UserCreationFail {
            get {
                return ResourceManager.GetString("Generic_UserCreationFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to retrieve user data.
        /// </summary>
        public static string Generic_UserFail {
            get {
                return ResourceManager.GetString("Generic_UserFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The user is inactive. Please contact the system administrator.
        /// </summary>
        public static string Generic_UserInactive {
            get {
                return ResourceManager.GetString("Generic_UserInactive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Already Used, trye again.
        /// </summary>
        public static string Generic_UserNameAlreadyUsed {
            get {
                return ResourceManager.GetString("Generic_UserNameAlreadyUsed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This user is active but has no role assigned.
        /// </summary>
        public static string Generic_UserNoRoleAssigned {
            get {
                return ResourceManager.GetString("Generic_UserNoRoleAssigned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Gateway received an invalid response.
        /// </summary>
        public static string httpCode_BadGatewayMsg {
            get {
                return ResourceManager.GetString("httpCode_BadGatewayMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bad Gateway.
        /// </summary>
        public static string httpCode_BadGatewayTitle {
            get {
                return ResourceManager.GetString("httpCode_BadGatewayTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Something went wrong.
        /// </summary>
        public static string HttpCode_BadRequestMsg {
            get {
                return ResourceManager.GetString("HttpCode_BadRequestMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bad Request.
        /// </summary>
        public static string HttpCode_BadRequestTitle {
            get {
                return ResourceManager.GetString("HttpCode_BadRequestTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You don&apos;t have permission to access this resource.
        /// </summary>
        public static string HttpCode_ForbiddenMsg {
            get {
                return ResourceManager.GetString("HttpCode_ForbiddenMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forbidden.
        /// </summary>
        public static string HttpCode_ForbiddenTile {
            get {
                return ResourceManager.GetString("HttpCode_ForbiddenTile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Server took too long to respond.
        /// </summary>
        public static string httpCode_GeteWayTimeMsg {
            get {
                return ResourceManager.GetString("httpCode_GeteWayTimeMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gateway Timeout.
        /// </summary>
        public static string httpCode_GeteWayTimeTitle {
            get {
                return ResourceManager.GetString("httpCode_GeteWayTimeTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Name or Password invalid.
        /// </summary>
        public static string HttpCode_LoginMsg {
            get {
                return ResourceManager.GetString("HttpCode_LoginMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login Error.
        /// </summary>
        public static string HttpCode_LoginTitle {
            get {
                return ResourceManager.GetString("HttpCode_LoginTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The requested resource could not be found.
        /// </summary>
        public static string HttpCode_NotFoundMsg {
            get {
                return ResourceManager.GetString("HttpCode_NotFoundMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not Found.
        /// </summary>
        public static string HttpCode_NotFoundTitle {
            get {
                return ResourceManager.GetString("HttpCode_NotFoundTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An unexpected error occurred on the Server.
        /// </summary>
        public static string HttpCode_ServerErrorMsg {
            get {
                return ResourceManager.GetString("HttpCode_ServerErrorMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server Error.
        /// </summary>
        public static string HttpCode_ServerErrorTitle {
            get {
                return ResourceManager.GetString("HttpCode_ServerErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Server is currently Unavailable.
        /// </summary>
        public static string httpCode_ServiceMsg {
            get {
                return ResourceManager.GetString("httpCode_ServiceMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service Unavaible.
        /// </summary>
        public static string httpCode_ServiceTitle {
            get {
                return ResourceManager.GetString("httpCode_ServiceTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Request timed out.
        /// </summary>
        public static string httpCode_TimeoutMsg {
            get {
                return ResourceManager.GetString("httpCode_TimeoutMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Timeout.
        /// </summary>
        public static string httpCode_TimeoutTitle {
            get {
                return ResourceManager.GetString("httpCode_TimeoutTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are not Authorized to access this resource.
        /// </summary>
        public static string HttpCode_UnauthorizedDeniedMsg {
            get {
                return ResourceManager.GetString("HttpCode_UnauthorizedDeniedMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Access Denied.
        /// </summary>
        public static string HttpCode_UnauthorizedDeniedTitle {
            get {
                return ResourceManager.GetString("HttpCode_UnauthorizedDeniedTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your Session has expired.  Please Log In again..
        /// </summary>
        public static string HttpCode_UnauthorizedTokenMsg {
            get {
                return ResourceManager.GetString("HttpCode_UnauthorizedTokenMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Session Expired.
        /// </summary>
        public static string HttpCode_UnauthorizedTokenTitle {
            get {
                return ResourceManager.GetString("HttpCode_UnauthorizedTokenTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Server could not process the submitted data.
        /// </summary>
        public static string httpCode_UnprocessMsg {
            get {
                return ResourceManager.GetString("httpCode_UnprocessMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Data.
        /// </summary>
        public static string httpCode_UnprocessTitle {
            get {
                return ResourceManager.GetString("httpCode_UnprocessTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Job Position.
        /// </summary>
        public static string JobPosition {
            get {
                return ResourceManager.GetString("JobPosition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Name.
        /// </summary>
        public static string LastName {
            get {
                return ResourceManager.GetString("LastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logo.
        /// </summary>
        public static string Logo {
            get {
                return ResourceManager.GetString("Logo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want logout?.
        /// </summary>
        public static string LogoutMsg {
            get {
                return ResourceManager.GetString("LogoutMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logout System.
        /// </summary>
        public static string LogoutTitle {
            get {
                return ResourceManager.GetString("LogoutTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max Clients.
        /// </summary>
        public static string Max_Clients {
            get {
                return ResourceManager.GetString("Max_Clients", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Months.
        /// </summary>
        public static string Months {
            get {
                return ResourceManager.GetString("Months", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Record was successfully registered.
        /// </summary>
        public static string msg_CreateSuccessMessage {
            get {
                return ResourceManager.GetString("msg_CreateSuccessMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registered.
        /// </summary>
        public static string msg_CreateSuccessTitle {
            get {
                return ResourceManager.GetString("msg_CreateSuccessTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete this record?.
        /// </summary>
        public static string msg_DeleteConfirmationText {
            get {
                return ResourceManager.GetString("msg_DeleteConfirmationText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Confirmation.
        /// </summary>
        public static string msg_DeleteConfirmationTitle {
            get {
                return ResourceManager.GetString("msg_DeleteConfirmationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes, delete it.
        /// </summary>
        public static string msg_DeleteConfirmButton {
            get {
                return ResourceManager.GetString("msg_DeleteConfirmButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The record was successfully removed.
        /// </summary>
        public static string msg_DeleteMessage {
            get {
                return ResourceManager.GetString("msg_DeleteMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deleted.
        /// </summary>
        public static string msg_DeleteTitle {
            get {
                return ResourceManager.GetString("msg_DeleteTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome.
        /// </summary>
        public static string msg_LoginSuccessTitle {
            get {
                return ResourceManager.GetString("msg_LoginSuccessTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You will need to log in again to continue..
        /// </summary>
        public static string msg_LogoutConfirmationText {
            get {
                return ResourceManager.GetString("msg_LogoutConfirmationText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to log out?.
        /// </summary>
        public static string msg_LogoutConfirmationTitle {
            get {
                return ResourceManager.GetString("msg_LogoutConfirmationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log Out.
        /// </summary>
        public static string msg_LogoutConfirmButton {
            get {
                return ResourceManager.GetString("msg_LogoutConfirmButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The record was successfully updated.
        /// </summary>
        public static string msg_UpdateSuccessMessage {
            get {
                return ResourceManager.GetString("msg_UpdateSuccessMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updated.
        /// </summary>
        public static string msg_UpdateSuccessTitle {
            get {
                return ResourceManager.GetString("msg_UpdateSuccessTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please complete all required fields before continuing..
        /// </summary>
        public static string msg_ValidationWarningMessage {
            get {
                return ResourceManager.GetString("msg_ValidationWarningMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incomplete Form.
        /// </summary>
        public static string msg_ValidationWarningTitle {
            get {
                return ResourceManager.GetString("msg_ValidationWarningTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Origin.
        /// </summary>
        public static string Origin {
            get {
                return ResourceManager.GetString("Origin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password Recovery.
        /// </summary>
        public static string Password_Recovery {
            get {
                return ResourceManager.GetString("Password_Recovery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter your Email, User Name and new password to reset your account.
        /// </summary>
        public static string PasswordChangeMsg {
            get {
                return ResourceManager.GetString("PasswordChangeMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Password.
        /// </summary>
        public static string PasswordChangeTitle {
            get {
                return ResourceManager.GetString("PasswordChangeTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm Password.
        /// </summary>
        public static string PasswordConfirm {
            get {
                return ResourceManager.GetString("PasswordConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current Password.
        /// </summary>
        public static string PasswordCurrent {
            get {
                return ResourceManager.GetString("PasswordCurrent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Password.
        /// </summary>
        public static string PasswordNew {
            get {
                return ResourceManager.GetString("PasswordNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recovery Password.
        /// </summary>
        public static string PasswordRecovery {
            get {
                return ResourceManager.GetString("PasswordRecovery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your Password has been changed successfully.
        /// </summary>
        public static string PasswordUpdateMsg {
            get {
                return ResourceManager.GetString("PasswordUpdateMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password Update.
        /// </summary>
        public static string PasswordUpdateTitle {
            get {
                return ResourceManager.GetString("PasswordUpdateTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone.
        /// </summary>
        public static string Phone {
            get {
                return ResourceManager.GetString("Phone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Photo.
        /// </summary>
        public static string Photo {
            get {
                return ResourceManager.GetString("Photo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plan.
        /// </summary>
        public static string Plan {
            get {
                return ResourceManager.GetString("Plan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price.
        /// </summary>
        public static string Price {
            get {
                return ResourceManager.GetString("Price", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product.
        /// </summary>
        public static string Product {
            get {
                return ResourceManager.GetString("Product", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role User.
        /// </summary>
        public static string RoleUser {
            get {
                return ResourceManager.GetString("RoleUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Select Country].
        /// </summary>
        public static string Select_Country {
            get {
                return ResourceManager.GetString("Select_Country", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Select Plan].
        /// </summary>
        public static string Select_Plan {
            get {
                return ResourceManager.GetString("Select_Plan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Select Role].
        /// </summary>
        public static string Select_Role {
            get {
                return ResourceManager.GetString("Select_Role", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to State.
        /// </summary>
        public static string State {
            get {
                return ResourceManager.GetString("State", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to States.
        /// </summary>
        public static string States {
            get {
                return ResourceManager.GetString("States", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transaction Already Active.
        /// </summary>
        public static string Transaction_AlreadyActive {
            get {
                return ResourceManager.GetString("Transaction_AlreadyActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transaction No Active To Commit.
        /// </summary>
        public static string Transaction_NoActiveToCommit {
            get {
                return ResourceManager.GetString("Transaction_NoActiveToCommit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transaction No Active To Rollback.
        /// </summary>
        public static string Transaction_NoActiveToRollback {
            get {
                return ResourceManager.GetString("Transaction_NoActiveToRollback", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User.
        /// </summary>
        public static string User {
            get {
                return ResourceManager.GetString("User", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UserName.
        /// </summary>
        public static string UserName {
            get {
                return ResourceManager.GetString("UserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UserType.
        /// </summary>
        public static string UserType {
            get {
                return ResourceManager.GetString("UserType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Between {2} and {1} characters long.
        /// </summary>
        public static string Validation_BetweenLength {
            get {
                return ResourceManager.GetString("Validation_BetweenLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No item selected.
        /// </summary>
        public static string Validation_Combo {
            get {
                return ResourceManager.GetString("Validation_Combo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is not a valid email address.
        /// </summary>
        public static string Validation_InvalidEmail {
            get {
                return ResourceManager.GetString("Validation_InvalidEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Format.
        /// </summary>
        public static string Validation_InvalidFormat {
            get {
                return ResourceManager.GetString("Validation_InvalidFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot be longer than {1} characteres.
        /// </summary>
        public static string Validation_MaxLength {
            get {
                return ResourceManager.GetString("Validation_MaxLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Must be at least {1} characters long.
        /// </summary>
        public static string Validation_MinLength {
            get {
                return ResourceManager.GetString("Validation_MinLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Passwords do not match.
        /// </summary>
        public static string Validation_PasswordMismatch {
            get {
                return ResourceManager.GetString("Validation_PasswordMismatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must select a valid {0}.
        /// </summary>
        public static string Validation_Range {
            get {
                return ResourceManager.GetString("Validation_Range", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Field is required.
        /// </summary>
        public static string Validation_Required {
            get {
                return ResourceManager.GetString("Validation_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Between {2} and {1}characters long.
        /// </summary>
        public static string Validation_StringLength {
            get {
                return ResourceManager.GetString("Validation_StringLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The username can only contain letters and numbers.
        /// </summary>
        public static string Validation_UserNameFormat {
            get {
                return ResourceManager.GetString("Validation_UserNameFormat", resourceCulture);
            }
        }
    }
}
